name: BGforge Handle Charsets
description: Handle charsets for WeiDU mods
branding:
  icon: message-circle
  color: green

inputs:
  tra_path:
    description: Tra source directory
    required: true
  out_path:
    description: Converted tra output directory
    required: true
  from_utf8:
    description: Convert From UTF-8
    required: false
    default: false
  split_console:
    description: Generate OS-specific files from setup.tra and install.tra
    required: false
    default: false
  commit:
    description: Commit if changes are found
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Handle charsets
      shell: bash
      run: $GITHUB_ACTION_PATH/action.sh
      env:
        INPUT_TRA_PATH: ${{ inputs.tra_path }}
        INPUT_OUT_PATH: ${{ inputs.out_path }}
        INPUT_FROM_UTF8: ${{ inputs.from_utf8 }}
        INPUT_SPLIT_CONSOLE: ${{ inputs.split_console }}
        INPUT_COMMIT: ${{ inputs.commit }}
